# Generated by Django 3.0 on 2019-12-12 11:15

from django.db import migrations, models
import django.db.models.deletion
import pizza.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstancePizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('city', models.CharField(default='Одесса', max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('apartment', models.CharField(max_length=20, verbose_name='Квартира')),
                ('front_door', models.PositiveIntegerField(verbose_name='Парадная')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('number_persons', models.PositiveIntegerField(default=1, verbose_name='Кол-во персон:')),
                ('comment', models.CharField(max_length=300, verbose_name='Комментарий')),
                ('type_payment', models.CharField(max_length=100, verbose_name='Способ оплаты')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=pizza.models.image_folder)),
                ('slug', models.SlugField()),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('ingredient', models.ManyToManyField(to='pizza.Ingredient', verbose_name='Ингридиенты')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Пиццу',
                'verbose_name_plural': 'Пиццы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('pizzas', models.ManyToManyField(blank=True, to='pizza.InstancePizza')),
            ],
        ),
        migrations.AddField(
            model_name='instancepizza',
            name='pizza_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza'),
        ),
        migrations.AddField(
            model_name='instancepizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Size', verbose_name='Размер'),
        ),
    ]
